/* Auto-generated by download_images.py -- do not edit manually */
/* Regenerate: python download_images.py */
window.IMG_DATA = {
  "angels": [
    {
      "src": "images/angels/img_01.jpg",
      "cap": "Angel's Landing, Sunrise, Zion N.P. 5-1-14 (14351035551)"
    },
    {
      "src": "images/angels/img_02.jpg",
      "cap": "Angel's Landing Summit"
    },
    {
      "src": "images/angels/img_03.jpg",
      "cap": "Angels Landing, Zion Canyon, Zion National Park, Utah (10261"
    },
    {
      "src": "images/angels/img_04.jpg",
      "cap": "Angels Landing, Zion Canyon, Zion National Park, Utah (10261"
    },
    {
      "src": "images/angels/img_05.jpg",
      "cap": "Angels Landing, Zion Canyon, Zion National Park, Utah (68919"
    }
  ],
  "bandelier": [
    {
      "src": "images/bandelier/img_01.jpg",
      "cap": "Above Bandelier National Monument"
    },
    {
      "src": "images/bandelier/img_02.jpg",
      "cap": "Band backcountry"
    },
    {
      "src": "images/bandelier/img_03.jpg",
      "cap": "Bandelier (31629997483)"
    },
    {
      "src": "images/bandelier/img_04.jpg",
      "cap": "Bandelier (3354228238)"
    },
    {
      "src": "images/bandelier/img_05.jpg",
      "cap": "Bandelier (5325566573)"
    }
  ],
  "cathedral": [
    {
      "src": "images/cathedral/img_01.jpg",
      "cap": "Doe Mountain Trail No. 60 - 19297865534"
    },
    {
      "src": "images/cathedral/img_02.jpg",
      "cap": "IMG_1564"
    },
    {
      "src": "images/cathedral/img_03.jpg",
      "cap": "IMG_1565"
    },
    {
      "src": "images/cathedral/img_04.jpg",
      "cap": "Sedona, Cathedral Rock, Airport"
    },
    {
      "src": "images/cathedral/img_05.jpg",
      "cap": "Secret Slickrock"
    },
    {
      "src": "images/cathedral/img_06.jpg",
      "cap": "Cathedral of Light"
    }
  ],
  "checkerboard": [
    {
      "src": "images/checkerboard/img_01.jpg",
      "cap": "Checkerboard Mesa, Zion-Mt. Carmel Highway, East End of Zion"
    },
    {
      "src": "images/checkerboard/img_02.jpg",
      "cap": "Checkerboard Mesa, Zion-Mt. Carmel Highway, East End of Zion"
    },
    {
      "src": "images/checkerboard/img_03.jpg",
      "cap": "Checkerboard Mesa, Zion-Mt. Carmel Highway, East End of Zion"
    },
    {
      "src": "images/checkerboard/img_04.jpg",
      "cap": "Checkerboard Mesa, Zion National Park, Utah (8096074402)"
    }
  ],
  "cloudcroft": [
    {
      "src": "images/cloudcroft/img_01.jpg",
      "cap": "New Mexico, the land of the delight makers - the history of "
    },
    {
      "src": "images/cloudcroft/img_02.jpg",
      "cap": "Between Realms."
    },
    {
      "src": "images/cloudcroft/img_03.jpg",
      "cap": "Cloudcroft sleep overs"
    },
    {
      "src": "images/cloudcroft/img_04.jpg",
      "cap": "Tunnel Vista Observation Site"
    },
    {
      "src": "images/cloudcroft/img_05.jpg",
      "cap": "Tunnel Vista Observation Site"
    }
  ],
  "cloudmorn": [
    {
      "src": "images/cloudmorn/img_01.jpg",
      "cap": "Lincoln National Forest"
    },
    {
      "src": "images/cloudmorn/img_02.jpg",
      "cap": "Lincoln National Forest"
    },
    {
      "src": "images/cloudmorn/img_03.jpg",
      "cap": "Lincoln National Forest"
    },
    {
      "src": "images/cloudmorn/img_04.jpg",
      "cap": "Lincoln National Forest"
    }
  ],
  "emerald": [
    {
      "src": "images/emerald/img_01.jpg",
      "cap": "img 01"
    },
    {
      "src": "images/emerald/img_02.jpg",
      "cap": "img 02"
    },
    {
      "src": "images/emerald/img_03.jpg",
      "cap": "img 03"
    },
    {
      "src": "images/emerald/img_04.jpg",
      "cap": "img 04"
    },
    {
      "src": "images/emerald/img_05.jpg",
      "cap": "img 05"
    }
  ],
  "humphreys": [
    {
      "src": "images/humphreys/img_01.jpg",
      "cap": "Humphreys Peak"
    },
    {
      "src": "images/humphreys/img_02.jpg",
      "cap": "Humphreys Peak"
    },
    {
      "src": "images/humphreys/img_03.jpg",
      "cap": "Humphreys Peak"
    },
    {
      "src": "images/humphreys/img_04.jpg",
      "cap": "Nature Trail"
    },
    {
      "src": "images/humphreys/img_05.jpg",
      "cap": "Ski Slopes"
    }
  ],
  "jemezfalls": [
    {
      "src": "images/jemezfalls/img_01.jpg",
      "cap": "Jemez Falls 1"
    },
    {
      "src": "images/jemezfalls/img_02.jpg",
      "cap": "Jemez Falls 2"
    }
  ],
  "jemezmtn": [
    {
      "src": "images/jemezmtn/img_01.jpg",
      "cap": "Jemez Road Trip-4"
    },
    {
      "src": "images/jemezmtn/img_02.jpg",
      "cap": "Jemez Road Trip-6"
    },
    {
      "src": "images/jemezmtn/img_03.jpg",
      "cap": "Jemez Road Trip-11"
    },
    {
      "src": "images/jemezmtn/img_04.jpg",
      "cap": "Jemez Road Trip-9"
    }
  ],
  "kolob": [
    {
      "src": "images/kolob/img_01.jpg",
      "cap": "1977 Zion in fall"
    },
    {
      "src": "images/kolob/img_03.jpg",
      "cap": "Arches in Kolob Canyons"
    },
    {
      "src": "images/kolob/img_04.jpg",
      "cap": "Bryce & Zion with Backroads (15208688167)"
    },
    {
      "src": "images/kolob/img_05.jpg",
      "cap": "Calochortus nuttallii Sego lily Utah"
    },
    {
      "src": "images/kolob/img_06.jpg",
      "cap": "Clouds over Kolob Canyon, Utah 8-12 (15196571749)"
    }
  ],
  "meteor": [
    {
      "src": "images/meteor/img_01.jpg",
      "cap": "Blast From the Past- Arizona’s Meteor Crater (154497)"
    },
    {
      "src": "images/meteor/img_03.jpg",
      "cap": "Earth from Space- Meteor Crater ESA499187"
    },
    {
      "src": "images/meteor/img_04.jpg",
      "cap": "Impact crater (close-up)"
    }
  ],
  "narrows": [
    {
      "src": "images/narrows/img_01.jpg",
      "cap": "img 01"
    },
    {
      "src": "images/narrows/img_02.jpg",
      "cap": "img 02"
    },
    {
      "src": "images/narrows/img_03.jpg",
      "cap": "img 03"
    },
    {
      "src": "images/narrows/img_04.jpg",
      "cap": "img 04"
    },
    {
      "src": "images/narrows/img_05.jpg",
      "cap": "img 05"
    },
    {
      "src": "images/narrows/img_06.jpg",
      "cap": "img 06"
    },
    {
      "src": "images/narrows/img_07.jpg",
      "cap": "img 07"
    }
  ],
  "overlook": [
    {
      "src": "images/overlook/img_01.jpg",
      "cap": "Canyon Overlook Trail, Zion National Park (5521116975)"
    },
    {
      "src": "images/overlook/img_02.jpg",
      "cap": "Canyon Overlook Trail, Zion National Park (5521120381)"
    },
    {
      "src": "images/overlook/img_03.jpg",
      "cap": "Canyon Overlook Trail, Zion National Park (5521122167)"
    },
    {
      "src": "images/overlook/img_04.jpg",
      "cap": "Canyon Overlook Trail, Zion National Park (5521128993)"
    },
    {
      "src": "images/overlook/img_05.jpg",
      "cap": "Canyon Overlook Trail, Zion National Park (5521132377)"
    }
  ],
  "rimtrail": [
    {
      "src": "images/rimtrail/img_01.jpg",
      "cap": "N93A1265-1"
    },
    {
      "src": "images/rimtrail/img_02.jpg",
      "cap": "White Sands (38A) Deer"
    },
    {
      "src": "images/rimtrail/img_03.jpg",
      "cap": "White Sands (16A) Emptying White Sands"
    },
    {
      "src": "images/rimtrail/img_04.jpg",
      "cap": "Lincoln National Forest (57) Mule Deer"
    },
    {
      "src": "images/rimtrail/img_05.jpg",
      "cap": "Lincoln National Forest (17) Gray Fox"
    }
  ],
  "sacramento": [
    {
      "src": "images/sacramento/img_01.jpg",
      "cap": "New Mexico in 2010"
    },
    {
      "src": "images/sacramento/img_02.jpg",
      "cap": "New Mexico in 2010"
    },
    {
      "src": "images/sacramento/img_03.jpg",
      "cap": "New Mexico in 2010"
    },
    {
      "src": "images/sacramento/img_04.jpg",
      "cap": "Cloudcroft Trestle"
    }
  ],
  "sfpeaks": [
    {
      "src": "images/sfpeaks/img_01.jpg",
      "cap": "Abineau Trail is a steep 1,800 foot climb over two miles up "
    },
    {
      "src": "images/sfpeaks/img_02.jpg",
      "cap": "Abineau Trail is a steep 1,800 foot climb over two miles up "
    },
    {
      "src": "images/sfpeaks/img_03.jpg",
      "cap": "Abineau Trail is a steep 1,800 foot climb over two miles up "
    },
    {
      "src": "images/sfpeaks/img_04.jpg",
      "cap": "Abineau Trail is a steep 1,800 foot climb over two miles up "
    },
    {
      "src": "images/sfpeaks/img_05.jpg",
      "cap": "Arizona Snowbowl Grand Canyon Express Ski Lift Opening Celeb"
    }
  ],
  "sliderock": [
    {
      "src": "images/sliderock/img_01.jpg",
      "cap": "2023 Slide Rock State Park-0477"
    },
    {
      "src": "images/sliderock/img_02.jpg",
      "cap": "2023 Slide Rock State Park-0481"
    },
    {
      "src": "images/sliderock/img_03.jpg",
      "cap": "2023 Slide Rock State Park-0482"
    },
    {
      "src": "images/sliderock/img_04.jpg",
      "cap": "2023 Slide Rock State Park-0484"
    },
    {
      "src": "images/sliderock/img_05.jpg",
      "cap": "2023 Slide Rock State Park-0515"
    }
  ],
  "sunsetcrat": [
    {
      "src": "images/sunsetcrat/img_01.jpg",
      "cap": "Aa Trail head and O'Leary Peak (58d7cf8e-155d-451f-67ef-84c3"
    },
    {
      "src": "images/sunsetcrat/img_02.jpg",
      "cap": "Basalt at Sunset Crater (GeoDIL number - 2881)"
    },
    {
      "src": "images/sunsetcrat/img_03.jpg",
      "cap": "Double Crater AR1VDON00010001"
    },
    {
      "src": "images/sunsetcrat/img_04.jpg",
      "cap": "Frost on the Cinder Dunes (58df0d9e-155d-451f-6756-61fdc178a"
    },
    {
      "src": "images/sunsetcrat/img_05.jpg",
      "cap": "Frost on the Cinder Dunes (58e63d9a-155d-451f-67c2-030012c71"
    },
    {
      "src": "images/sunsetcrat/img_06.jpg",
      "cap": "Frost on the Cinder Dunes (58eeec03-155d-451f-67b8-c8efd8843"
    }
  ],
  "sunspot": [
    {
      "src": "images/sunspot/img_01.jpg",
      "cap": "DST at night"
    },
    {
      "src": "images/sunspot/img_03.jpg",
      "cap": "DST on clear day"
    },
    {
      "src": "images/sunspot/img_04.jpg",
      "cap": "DST with flowers"
    },
    {
      "src": "images/sunspot/img_05.jpg",
      "cap": "Dunn with Clouds"
    }
  ],
  "trestle": [
    {
      "src": "images/trestle/img_01.jpg",
      "cap": "Cloudcroft Banner"
    },
    {
      "src": "images/trestle/img_02.jpg",
      "cap": "Forest Service Sign Mexican Canyon Trestle"
    },
    {
      "src": "images/trestle/img_03.jpg",
      "cap": "Mexican Canyon Trestle Cloudcroft New Mexico"
    },
    {
      "src": "images/trestle/img_04.jpg",
      "cap": "Mexican Canyon Trestle from the lookout (5032007085)"
    }
  ],
  "valles": [
    {
      "src": "images/valles/img_01.jpg",
      "cap": "A distant group of snowshoers on the Cerro La Jara Loop. (57"
    },
    {
      "src": "images/valles/img_02.jpg",
      "cap": "A distant line of snowshoers hikes into the sunset in Valle "
    },
    {
      "src": "images/valles/img_03.jpg",
      "cap": "A forested hilltop, Cerro La Jara (acd5266e-7edc-4a9b-a222-e"
    },
    {
      "src": "images/valles/img_04.jpg",
      "cap": "A group of snowshoers hikes along the base of Cerro La Jara "
    },
    {
      "src": "images/valles/img_05.jpg",
      "cap": "A Gunnison's prairie dog along the Cerro La Jara Loop. (f0b9"
    },
    {
      "src": "images/valles/img_06.jpg",
      "cap": "A large boulder at the edge of Valle Grande. (cb26eb6f-6cb9-"
    }
  ],
  "walnut": [
    {
      "src": "images/walnut/img_01.jpg",
      "cap": "1000-year old homes in Walnut Canyon"
    },
    {
      "src": "images/walnut/img_02.jpg",
      "cap": "Along Old Rt. 66, Flagstaff, AZ, Walnut Canyon 2005 (6680719"
    },
    {
      "src": "images/walnut/img_03.jpg",
      "cap": "Along Old Rt. 66, Flagstaff, AZ, Walnut Canyon 2005 (6680720"
    },
    {
      "src": "images/walnut/img_04.jpg",
      "cap": "Cliffs at Walnut Canyon (GeoDIL number - 2878)"
    },
    {
      "src": "images/walnut/img_05.jpg",
      "cap": "Cliffs at Walnut Canyon (GeoDIL number - 2879)"
    }
  ],
  "whitesands": [
    {
      "src": "images/whitesands/img_02.jpg",
      "cap": "Dual Marvels of New Mexico (MODIS)"
    },
    {
      "src": "images/whitesands/img_03.jpg",
      "cap": "NM White Sands 1"
    },
    {
      "src": "images/whitesands/img_04.jpg",
      "cap": "New Mexico (MODIS 2019-09-29)"
    },
    {
      "src": "images/whitesands/img_05.jpg",
      "cap": "New Mexico (MODIS 2020-11-20)"
    },
    {
      "src": "images/whitesands/img_06.jpg",
      "cap": "White Sands NM (GeoDIL number - 315)"
    },
    {
      "src": "images/whitesands/img_07.jpg",
      "cap": "White Sands NM (GeoDIL number - 316)"
    }
  ],
  "wupatki": [
    {
      "src": "images/wupatki/img_01.jpg",
      "cap": "A Look at Wupatki Construction"
    },
    {
      "src": "images/wupatki/img_02.jpg",
      "cap": "A Thousand Year Old View"
    },
    {
      "src": "images/wupatki/img_03.jpg",
      "cap": "Archaeologist Kelly Teaches Kids About Pottery (bcc933af-155"
    },
    {
      "src": "images/wupatki/img_04.jpg",
      "cap": "Archaeologist Kelly Teaches Kids About Pottery (bcef54fd-155"
    },
    {
      "src": "images/wupatki/img_05.jpg",
      "cap": "Archaeologists and Visitors Try Their Hand at Ancient Spear "
    }
  ],
  "gilman": [
    {
      "src": "images/gilman/img_01.jpg",
      "cap": "Gilman Tunnels (3679124645)"
    },
    {
      "src": "images/gilman/img_02.jpg",
      "cap": "Gilman Tunnels (4172481211)"
    },
    {
      "src": "images/gilman/img_03.jpg",
      "cap": "Gilman tunnels 1"
    },
    {
      "src": "images/gilman/img_04.jpg",
      "cap": "Gilman tunnels 2"
    }
  ],
  "battleship": [
    {
      "src": "images/battleship/img_01.jpg",
      "cap": "IMG_9301-2"
    },
    {
      "src": "images/battleship/img_02.jpg",
      "cap": "Battleship Rock"
    },
    {
      "src": "images/battleship/img_03.jpg",
      "cap": "IMGP5895"
    },
    {
      "src": "images/battleship/img_04.jpg",
      "cap": "IMGP5893"
    }
  ]
};
